dist: xenial
sudo: true
language: python

matrix:
  include:
    - python: "3.6"
      env: "DJANGO_VERSION=2.2"
    - python: "3.6"
      env: "DJANGO_VERSION=3.1"
    - python: "3.6"
      env: "DJANGO_VERSION=3.2"
    - python: "3.7"
      env: "DJANGO_VERSION=2.2"
    - python: "3.7"
      env: "DJANGO_VERSION=3.1"
    - python: "3.7"
      env: "DJANGO_VERSION=3.2"
    - python: "3.8"
      env: "DJANGO_VERSION=2.2"
    - python: "3.8"
      env: "DJANGO_VERSION=3.1"
    - python: "3.8"
      env: "DJANGO_VERSION=3.2"
    - python: "3.9"
      env: "DJANGO_VERSION=2.2"
    - python: "3.9"
      env: "DJANGO_VERSION=3.1"
    - python: "3.9"
      env: "DJANGO_VERSION=3.2"


install:
  - "pip install mock"
  - "pip install \"django>=$DJANGO_VERSION\""
  - "python setup.py develop"
  - "pip install pytest-django"

script:
  - "python -m pytest"
